### ISSUE TITLE
Dev - Referal / point 

### ISSUE THREAD

**Issue by Amritx** [thirtydigital/teachest#54]
Points for each delivery
Points for 10 or 15 subs
Points for tweeting link / hashtag
Points for recommending service
Points for friends sign up 
Points for linking social accounts
Points for following Twitter / instagram / facebook / google plus 
Points for retweeting

basically every action that could lead to a subscriber needs to be rewarded. The first plugin doesn't do any of the social stuff.

**Comment by andygirvan** [comment]
Sumo - install on dev site and see what happens
