### ISSUE TITLE
Adwords retargeting pixle on site

### ISSUE THREAD

**Issue by Amritx** [thirtydigital/teachest#61]
It is for the google targeting display ads

**Comment by Amritx** [comment]
---

Open comment to "edit" and the code is within the body of the comment section. 

## Not sure what I'm, meant to put in here --> REPLACE_WITH_VALUE Any value?





<script type="text/javascript">
var google_tag_params = {
ecomm_prodid: 'REPLACE_WITH_VALUE',
ecomm_pagetype: 'REPLACE_WITH_VALUE',
ecomm_totalvalue: 'REPLACE_WITH_VALUE',
};
</script>

<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 933837722;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>

<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>

<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/933837722/?value=1&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

**Comment by andygirvan** [comment]
The custom values are only needed if you have any custom values req.

**Comment by andygirvan** [comment]
This should do it:

```
<!-- Google Code for Remarketing Tag -->
<!--------------------------------------------------
Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup
--------------------------------------------------->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 933837722;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/933837722/?value=1&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
```

So you want this on the conversion/thank you page?

**Comment by Amritx** [comment]
Should this not be on all pages? It is meant to drop a cookie on all users machines so they see TeaChest display ads?

**Comment by andygirvan** [comment]
Ok cool, I can whack this in the footer and let you know when done
